# Generated by Django 4.2 on 2024-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Longitude')),
                ('detailing_type', models.CharField(choices=[('current', 'Current'), ('minutely', 'Minutely'), ('hourly', 'Hourly'), ('daily', 'Daily')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenWeatherMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Longitude')),
                ('timestamp', models.DateTimeField()),
                ('response', models.TextField()),
            ],
            options={
                'unique_together': {('lat', 'lon')},
            },
        ),
    ]
